version: "2"
services:
    consul:
        command: agent -server -bootstrap-expect=1 -client=0.0.0.0
        image: consul:latest

    registrator:
        command: -internal consul://consul:8500
        image: gliderlabs/registrator:latest
        links:
            - consul
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock"

    cadvisor:
        image: google/cadvisor:latest
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"
        ports:
            - "8081:8080"

    prometheus:
        build: ./prometheus
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        links:
            - cadvisor
            - consul

    haproxy:
        build: ./haproxy
        links:
            - consul
        depends_on:
            - registrator

    nginx:
        build: ./nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - haproxy

    php:
        mem_limit: 200m
        environment:
            - SERVICE_NAME=app
            - SERVICE_TAGS=php
        build: ./php
        volumes:
            - ./php/src:/src
        depends_on:
            - haproxy 

